services:
  theja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theja_app
    ports:
      # Puerto externo (host) 3003 hacia el puerto interno 3000 del contenedor
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Opción 1 (Recomendada): Volumen nombrado gestionado por Docker (aísla y protege SQLite)
      - theja_db_data:/app/database
      # Opción 2: Mapeo directo a la carpeta local (descomenta si deseas ver theja.db en tu máquina)
      # - ./database:/app/database
    restart: unless-stopped

volumes:
  theja_db_data:
    driver: local
